on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              pyinstaller --onefile --console -n JioTV -i resources/JioTV_logo.icns main.py &&
              cp -r templates dist &&
              cp -r data dist &&
              cp -r static dist &&
              cd dist/ &&
              zip -r9 JioTV_auto_build_MACOS_x86_64 .
            OUT_FILE_NAME: JioTV_auto_build_MACOS_x86_64.zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
              pyinstaller --onefile --console -n JioTV  -i resources\JioTV_logo.ico main.py &&
              cp -r templates dist &&
              cp -r data dist &&
              cp -r static dist &&
              cd dist/ &&
              powershell Compress-Archive -Path .\* -DestinationPath JioTV_auto_build_WINDOWS_x86_64.zip
            OUT_FILE_NAME: JioTV_auto_build_WINDOWS_x86_64.zip
            ASSET_MIME: application/zip
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: >
              pyinstaller --onefile --console -n JioTV main.py &&
              cp -r templates dist &&
              cp -r data dist &&
              cp -r static dist &&
              cd dist/ &&
              zip -r9 JioTV_auto_build_LINUX_x86_64 .
            OUT_FILE_NAME: JioTV_auto_build_LINUX_x86_64.zip
            ASSET_MIME: application/zip
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.X
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{matrix.OUT_FILE_NAME}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
